#!/bin/bash

python 002_Lagging_Indicator_US_GDP.py
python 003_Lagging_Indicator_World_GDP.py
python 005_Lagging_Indicator_Job_Market_US_World.py
python 006_Lagging_Indicator_Personal_Consumption_Expenditures.py
python 007_Lagging_Indicator_US_Inflation.py
python 008_Lagging_Indicator_Global_Inflation.py
python 009_Lagging_Indicator_US_Industrial_Production.py
python 010_Lagging_Indicator_World_Industrial_Production.py
python 011_Lagging_Indicator_Retail_Sales.py
python 012_Central_Banks.py
python 013_Interest_Rates.py
python 014_US_Global_Money_Supply.py
python 015_Leading_Indicator_US_Consumer_Confidence.py
python 016_Leading_Indicator_US_ISM_Manufacturing.py